"""Pydantic schemas for API request/response models."""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field

# --- Request Schemas ---


class RecommendationRequest(BaseModel):
    """Request for book recommendations."""

    favorite_books: list[str] = Field(
        ...,
        min_length=3,
        max_length=5,
        description="List of 3-5 favorite book titles or ISBNs",
    )
    num_recommendations: int = Field(default=10, ge=1, le=20)


class BookSearchRequest(BaseModel):
    """Request to search and ingest a book."""

    query: str = Field(..., min_length=1, max_length=200)


class ScrapeRequest(BaseModel):
    """Request to scrape reviews for a book."""

    max_reviews: int = Field(default=10, ge=1, le=20)


# --- Response Schemas ---


class BookMetadata(BaseModel):
    """Book metadata from APIs."""

    id: int
    title: str
    authors: list[str]
    subjects: list[str]
    description: Optional[str] = None
    isbn_13: Optional[str] = None
    isbn_10: Optional[str] = None
    open_library_key: Optional[str] = None
    google_books_id: Optional[str] = None
    cover_url: Optional[str] = None
    publish_year: Optional[int] = None
    page_count: Optional[int] = None
    average_rating: Optional[float] = None
    created_at: datetime


class ReviewSummary(BaseModel):
    """A scraped review summary."""

    id: int
    book_id: int
    source: str
    review_text: str
    rating: Optional[float] = None
    reviewer: Optional[str] = None


class TasteProfile(BaseModel):
    """User taste profile generated by Agent 1."""

    preferred_genres: list[str]
    preferred_themes: list[str]
    preferred_authors: list[str]
    reading_style: str
    summary: str


class RecommendationItem(BaseModel):
    """A single book recommendation with explanation."""

    book: BookMetadata
    score: float = Field(..., description="Similarity score 0-1")
    explanation: str = Field(..., description="2-3 sentence explanation")


class RecommendationResponse(BaseModel):
    """Full recommendation response."""

    recommendations: list[RecommendationItem]
    taste_profile: TasteProfile
    metrics: dict


class HealthResponse(BaseModel):
    """Health check response."""

    status: str
    version: str
    database: str
    redis: str


class MetricsResponse(BaseModel):
    """Aggregate metrics response."""

    total_requests: int
    total_tokens: int
    total_cost_usd: float
    avg_latency_s: float
    model_usage: dict[str, int]
